config/routes.rb
MultiButtonTest::Application.routes.draw do
  resources :projects do
    put 'complete', on: :collection
    put 'uncomplete', on: :collection
    delete 'group_destroy', on: :collection
  end

  root 'projects#index'

  

end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects2 = Project.where(:completed_at => nil)
    @projects1 = Project.where.not(:completed_at => nil)
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if params[:preview_button] || !@project.save
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      else
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  def group_destroy
    Project.delete_all(:id => params[:proj_ids])
    redirect_to projects_path
  end

  def complete
    Project.update_all(["completed_at=?", Time.now], :id => params[:proj_ids])
    redirect_to projects_path
  end

  def uncomplete
    Project.update_all(["completed_at=?", nil], :id => params[:proj_ids])
    redirect_to projects_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MultiButtonTest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>

<% if params[:preview_button] %>
  <%= @project.name %>
  <%= @project.description %>
<% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= submit_tag "submit"%>
    <%= submit_tag "preview", :name => "preview_button" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<h2>Complete Projects</h2>
<%= form_tag uncomplete_projects_path, :method => "put" do %>
<ul>
    <% @projects1.each do |project| %>
      <li>
        <%= check_box_tag "proj_ids[]", project.id %>
        <%= project.name %>
      </li>
    <% end %>
</ul> 
<%= submit_tag "Un-complete" %>
<% end %>

<h2>Un-complete Projects</h2>
<%= form_tag complete_projects_path, :method => "put" do %>
<ul>
    <% @projects2.each do |project| %>
      <li>
        <%= check_box_tag "proj_ids[]", project.id %>
        <%= project.name %>
      </li>
    <% end %>
</ul> 
<%= submit_tag "Complete" %> 
<% end %>

<h2>All Projects</h2>
<%= form_tag group_destroy_projects_path, :method => "delete" do %>
<ul>
    <% @projects.each do |project| %>
      <li>
        <%= check_box_tag "proj_ids[]", project.id %>
        <%= project.name %>
      </li>
    <% end %>
    <%= submit_tag "group delete" %> 
</ul> 
<% end %>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>